language: node_js
node_js:
  - "11"

env:
  global:
    # GITHUB_TOKEN
    - secure: "TlGoMax68mpZLcnNgW/c9uN8qS0XRtNBmXbbCmbYH3zq6uw3s9fi3yR87XLwITEeFKY9oa8ijDNnZsTJXBJdYaPMmGsc2Pnz98deX4J51SflrDZp4eta5LJocIA2O0FYa8rABJaTwtSwkEZt79+P9v8UFxk+64xDWJHcUbpOgKsIhM4DRxLnwkQcer62mmP3xJbD/lvetmrekcKmWZgNeW8sIyXCYAJeMkgKmwtXKwWeiQnFiyBl5/qaMuW2+HSusCDzUPd2ZssRp793JTrieX7tm38ipn/YD02Nn2cEsF17GfTDXGQGUjpJgey52N3c44a9kFhU90y4rsbBFHYpkEFiz9CL9OnpBnmnnKi46cn6RBbBtXd5oaJaNHjwRA9VsDN2OJtud9qIUznEZ0+y4Wn5U0XNgYcnojvBptFxs2QDVOZmvoyXfhZpo2ynf2gltwc/ZWUYIRkkOft6f5sk9JEymhTcLdS0OKbhibGSgO3UZboK1+xtpbyhYK5RIFaPwSMEFHsS9ozUil4nU9+Vla8n/9FKsl0cJMwrlNcKCMJ+t065xW0gk+gdB5oTALib7p8eV/j9+nvSZvZhqxhVFUwsA3OaOONhoYPQ8e00InQBjmOb6n47XgLVt+izs8Ft+XhU2nb55m17eFzJ9S9zihqOAVzjA4uJRJv3nfYQfX0="
    # DOCKER_PASSWORD
    - secure: "IsYUu3uHTTJQDoW8kZLlEE7bX5CqX0oZoSpTHqs5hlLMNvcYJ6r2nfONZ1ZnNgYf6RP2Q0tLpU9SJsSA88X7Bf+I4nkLipHo4762VN/Djm8GGNcN2GK0WjTixdkcpaXAwRCUKV6SWsMvlWxdw2TnntUGl9VtCj0KsY3fvh5g1KMv80YcIpi61fpbV5ajVH7BQwGjGU136NKYwa56UzD8KNGwK2R3kijAIn37cr2e+uu9LuW1+gvQrAn+q0+x5mpsGdAuXnOgdyEPa0y4TXrLJTkvdbfV1KEECdaRSQZpTjzxbkSqaQPL9vUq1/hgJUzjJUiNZNWQzLYnHc5h1tgWNQJ5wQ+hhGkPSg4PRdIg5JHHvOGNbu2ddgz+HEVqvr9j6EhXe7tGYBBsqxVUPTnG8QEPNBcl4y+DmRxSqEZIcfIpvXcjQG8jkbFQvqbRnSWjooZRUvLgsOI+xmgmQZkE+LjBzOYTiBMdkTcFaxMNnJta4e9Zh6LctKMUwXzNzJmYkkJA89BY4rvOLTtiekoDBH0eVMLZAcXr8Wly3ARdIC/RR5Gmy8gXOcozn2rDwwUJx759dfPtZjdnQMpepTuvSNim1ppw9Eup9Ax1fMYOSIHgPiTf6i5Zb/W0zQSUO9gjSWoR5wSeKw9arJ8JHlckIJWK1Xo/uutxBuWRXDeh6rI="

services:
  - docker

before_script:
  - wget https://github.com/maxwo/ci/releases/download/0.1.0/ci-0.1.0-sources.tar.gz -O - | tar -xz

script:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: ci/travis/docker_deploy.sh
    on:
      tags: true
      all_branches: true

  - provider: pages
    skip_cleanup: true
    local_dir: dist
    repo: maxwo/maxwo.github.io
    target_branch: master
    github_token: $GITHUB_TOKEN
    on:
      branch: master
