language: node_js
node_js:
  - "11"

env:
  global:
    - secure: "VTBPs/99WNJfxYK4DAQ+8b4nKYI+bfbot0/AnVt7YHNbcvKlAbyQdUEHvMvHax4cyGowVIrRDd3Swleq9ZMDQ6pgVpVdmU9+MR7eLwVKufv24EItH335MgNVxDty61kYmETDajvfACZk6RkXINOC+6fT8BQSXS8ECjBrgvyFRlDmAHPO6vXG1+xgdZlxdZNZ33nbsYj0OEgcxmhMBldFPha5O2fDg5EMIPMoKPMGWsV1y5JsG1xZRNbJWD1qHOMeKrUK3WTdI0+R+jnWlp76F5BVOJScE9SiHpuOUGSCvOSKPyutL3BAY8Z2wZB6wljWIpjOWD424/2AZyNhD12+HHSIWrwRasWUb2/TjdxBfFe5rpx+TyKEes8uCHkdh5bQVwHPeQDoKTfwCZqGTrNFOcgzI8pXJI4Nf58BlUFJeGAsA9zvto8WTfgo4rTXF2jtI5WWZCwqIwBG7esgC+PtkTSMzCh+y42cteZ+GP1sMYT7c6XtEY+vbnd7wxtkN98/WMRq9RjMnQbcgq9uF/VvZYlIZ2sS4F7ydy8W8BH7EV5BqbVxuUyElsZIZMUiqy/IB8cPGpSQh8ULLQTEF8Nv6wJtrS0rSpaCG2us/qRXwn4lDjzaelgQN2/6+eefF0Si+0AjvtvMeXrgQWZgtbiFFe+v6dUet35gXD0HmH1YoTo="
    - secure: "h/Npxv4y5KAax1nmva2YZUTv0ZgTr5EO3rLs6hVZUed+ufPb5AVBHkKTzsk2tZ2hWtztTVjr21tcg64AypSdM44nRCd+C6aQTUMtiDpXEHgQUESlaLftaMixQibAVK/Gjvn4Ph3NSOWSX8jVgVxC7IJ2Y7HWJHXGHz9NqDaLXn11tI16MWxo/9ulq4F1/vE2epnme2HtVk39OostenrtbjGvZWRW1EEOptNGUOWfSbyz5E6p1uq1kram8wrtwY4U2aiQHKY5eimvkwqYwpr10sfCfqIyNxk9uCFdtdtI1qCJnpWZJ9NrUqaKIAZyTI3Kp+msRJuwkuqohYoT7nTzescO9bcEzbFkcngLQTKUdMyL6nIMMmO2k3PkrfwU78ieGRWyd+JKdkNJXIhywbeU+IT/0Hea2ti8ZGW/mIysSJO886JJ90u7A9sXyedZRLezVyu3c7lOjpzItY9tNtMpRbvMzWGEhsawSOvOTPVIUI2GOS1enL9bcwJ+PH9nTD75gTgUB2EUjYzPcfzqN2YCjU5cdhxV9cZMHkIFr8j4kPRXtr5eo9Td82SHzhQJKJ7HbBKas/+4F14SZtagDNV+i0NK6VaWTOXzXPjGkhZCdrouxmHyVlYTj45B4fpbcphSaWGjxhYCLe2GyaxJO5Y9XaUoy8e7TOMKC5nh0wQuvco="

services:
  - docker

before_script:
  - npm run build

after_success:
  - wget https://github.com/maxwo/ci/releases/download/0.1.0/ci-0.1.0-sources.tar.gz -O - | tar -xz

deploy:
  - provider: script
    skip_cleanup: true
    script: ci/travis/docker_deploy.sh
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: ci/travis/docker_deploy.sh
    on:
      all_branches: true

  - provider: pages
    skip_cleanup: true
    local_dir: dist
    repo: maxwo/maxwo.github.io
    target_branch: master
    github_token: $GITHUB_TOKEN
    on:
      branch: master
