language: node_js

env:
  global:
    - REPO: maxwoj/resume
    - secure: "ZYOOU5bXAng9YK/DieZBiOLEVBuEzkWhowIqjmUB4ujf6TNJUrElXIKXggzIsNDvAEWyqM6yWp57lrKqiC5E3EXqUXne0nMNe7yslK2fy7H/0c6CZINidVJVV2EiEkMQT7fyl1BlJrAEkwDdOHKpoQxmBgc13bpBEmlGLGOeHIIE/Exh282TjpG7B6N5uHAv2SoDKKYpNEpPm/c6ZgBO57dXgdUP8epJtSB26Mg6ubQ2+m0xIuJTyBW0N0XHbGMeksw/oKGfkRi7FOT6/7gUB19vntkE9Y/fCL484CgdHrbO8VzyXc0JP2FdK8Yf64PlGz/QbuyBGSGHbLh2wxlPlbzzwrJ9y3hZDXC/l9AXKB29RGHyjjUo9rNkudBvd5mwFSi3lCmJrOzmp9v80bFhvOkSob09wjB0pUPyxtEO7PMKkL3j8frVCLxRKPnZPkxX1NGktnsjEnQiYK7gK4MsBEFdhcG/LQZs2ovJoIQd0MH1e9RvynVw7MM+ckgDQkawyzyca1p2eE4l46oRulp3m2b+SvPRFhRL5Ci2cSH74opEHio8Yc61WJtcHgffsHTdwRP4rFKnKbkxx8EfFSfiNo0zIhrIGTKl6CBbNlWQYwarn42vbMYigQgDc4+QMiPsKF5856HBS0bjEpua4Ttanz33Utpko8CUAC2s2n4C1eo="
    - secure: "27P1EPwJ1uqgpJtGzKOGCKRtDKKMXjIWw1nff1DwzLHuT0PVma5nyawF+AvV6o57HscRNhWnEFpgLWbsPXIFTmyOv5FCstzfWOBjugN+cX72vCa3V7lIVqxU+55v+P9Y0BHAsqliZbbQR8MoayXWnOwWcvXmrgNB6peo8WzuFfzMjjNzVF8PO2W38krPZPKh1IhDDpcGAGtUkLYWyhZXlFt7CucjBmIxZui7LOUEr3LTQAD9Q6RhYaNCKGDnjWGgjjO3dDR9lqGnYDECgHIHyYAKc/QFdl9q1ku4hioabIoP4wjmaKJKnUOzwsfk1oKk4pR7QV4IcCRHDNYr8pvqv2YwVdx0N1apemQxtctPNVxC5ehHup38DOtNJV6VImbLtejvJEQWYJSS/Oo54EfNMdncwp2ehm0u1Rsf9HJH41OxtQoMUYxC4ZNIs8g2yMY8Mqlew0lOLx1bsQU0HlFfKSaJLiuYW45MUKrNv8tRaj62Uyl9SeiujjMJox7AzmsBqHDCd/vpmrI9VPSucMzM41M3dEJEip3xdayTAkMkE08vwsLWBo9o+LcU/rWLPsPC2XyFozE6Ks3KBwHEmqKN5TMvjQRtoZfbQwfCpdDDtolatrAxCpYz/3SHNUco3699VSG9c0ujKpe3EtkwGVu0TFEFGSHnJdMmGgakHU5xTro="
    - secure: "h/Npxv4y5KAax1nmva2YZUTv0ZgTr5EO3rLs6hVZUed+ufPb5AVBHkKTzsk2tZ2hWtztTVjr21tcg64AypSdM44nRCd+C6aQTUMtiDpXEHgQUESlaLftaMixQibAVK/Gjvn4Ph3NSOWSX8jVgVxC7IJ2Y7HWJHXGHz9NqDaLXn11tI16MWxo/9ulq4F1/vE2epnme2HtVk39OostenrtbjGvZWRW1EEOptNGUOWfSbyz5E6p1uq1kram8wrtwY4U2aiQHKY5eimvkwqYwpr10sfCfqIyNxk9uCFdtdtI1qCJnpWZJ9NrUqaKIAZyTI3Kp+msRJuwkuqohYoT7nTzescO9bcEzbFkcngLQTKUdMyL6nIMMmO2k3PkrfwU78ieGRWyd+JKdkNJXIhywbeU+IT/0Hea2ti8ZGW/mIysSJO886JJ90u7A9sXyedZRLezVyu3c7lOjpzItY9tNtMpRbvMzWGEhsawSOvOTPVIUI2GOS1enL9bcwJ+PH9nTD75gTgUB2EUjYzPcfzqN2YCjU5cdhxV9cZMHkIFr8j4kPRXtr5eo9Td82SHzhQJKJ7HbBKas/+4F14SZtagDNV+i0NK6VaWTOXzXPjGkhZCdrouxmHyVlYTj45B4fpbcphSaWGjxhYCLe2GyaxJO5Y9XaUoy8e7TOMKC5nh0wQuvco="

services:
  - docker

before_script:
  - npm install
  - npm install -g gulp
  - gulp build

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker push $REPO
